name = "Testing-Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cbb7b79912a6efd7d8e01740b1ce70ae4f1b49e5b66e5cdf6e79a7500faf8e0"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
