name = "LittleTiles"
filename = "LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3100/846/LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar"
hash-format = "murmur2"
hash = "1954397940"

[update]
[update.curseforge]
file-id = 3100846
project-id = 257818
release-channel = "beta"
