name = "Moving Elevators"
filename = "movingelevators-1.2.28-mc1.12.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3128/619/movingelevators-1.2.28-mc1.12.jar"
hash-format = "murmur2"
hash = "531182341"

[update]
[update.curseforge]
file-id = 3128619
project-id = 373051
release-channel = "beta"
